/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchoolRouteImport } from './routes/school'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportCardStudentIdRouteImport } from './routes/report-card.$studentId'
import { Route as ListTeachersRouteImport } from './routes/list/teachers'
import { Route as ListSubjectsRouteImport } from './routes/list/subjects'
import { Route as ListStudentsRouteImport } from './routes/list/students'
import { Route as ListResultsRouteImport } from './routes/list/results'
import { Route as ListParentsRouteImport } from './routes/list/parents'
import { Route as ListMessagesRouteImport } from './routes/list/messages'
import { Route as ListLessonsRouteImport } from './routes/list/lessons'
import { Route as ListExamsRouteImport } from './routes/list/exams'
import { Route as ListEventsRouteImport } from './routes/list/events'
import { Route as ListClassesRouteImport } from './routes/list/classes'
import { Route as ListAttendanceRouteImport } from './routes/list/attendance'
import { Route as ListAssignmentsRouteImport } from './routes/list/assignments'
import { Route as ListAnnouncementsRouteImport } from './routes/list/announcements'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolRoute = SchoolRouteImport.update({
  id: '/school',
  path: '/school',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportCardStudentIdRoute = ReportCardStudentIdRouteImport.update({
  id: '/report-card/$studentId',
  path: '/report-card/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListTeachersRoute = ListTeachersRouteImport.update({
  id: '/list/teachers',
  path: '/list/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ListSubjectsRoute = ListSubjectsRouteImport.update({
  id: '/list/subjects',
  path: '/list/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ListStudentsRoute = ListStudentsRouteImport.update({
  id: '/list/students',
  path: '/list/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ListResultsRoute = ListResultsRouteImport.update({
  id: '/list/results',
  path: '/list/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ListParentsRoute = ListParentsRouteImport.update({
  id: '/list/parents',
  path: '/list/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ListMessagesRoute = ListMessagesRouteImport.update({
  id: '/list/messages',
  path: '/list/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ListLessonsRoute = ListLessonsRouteImport.update({
  id: '/list/lessons',
  path: '/list/lessons',
  getParentRoute: () => rootRouteImport,
} as any)
const ListExamsRoute = ListExamsRouteImport.update({
  id: '/list/exams',
  path: '/list/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const ListEventsRoute = ListEventsRouteImport.update({
  id: '/list/events',
  path: '/list/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ListClassesRoute = ListClassesRouteImport.update({
  id: '/list/classes',
  path: '/list/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const ListAttendanceRoute = ListAttendanceRouteImport.update({
  id: '/list/attendance',
  path: '/list/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const ListAssignmentsRoute = ListAssignmentsRouteImport.update({
  id: '/list/assignments',
  path: '/list/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ListAnnouncementsRoute = ListAnnouncementsRouteImport.update({
  id: '/list/announcements',
  path: '/list/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/school': typeof SchoolRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/list/announcements': typeof ListAnnouncementsRoute
  '/list/assignments': typeof ListAssignmentsRoute
  '/list/attendance': typeof ListAttendanceRoute
  '/list/classes': typeof ListClassesRoute
  '/list/events': typeof ListEventsRoute
  '/list/exams': typeof ListExamsRoute
  '/list/lessons': typeof ListLessonsRoute
  '/list/messages': typeof ListMessagesRoute
  '/list/parents': typeof ListParentsRoute
  '/list/results': typeof ListResultsRoute
  '/list/students': typeof ListStudentsRoute
  '/list/subjects': typeof ListSubjectsRoute
  '/list/teachers': typeof ListTeachersRoute
  '/report-card/$studentId': typeof ReportCardStudentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/school': typeof SchoolRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/list/announcements': typeof ListAnnouncementsRoute
  '/list/assignments': typeof ListAssignmentsRoute
  '/list/attendance': typeof ListAttendanceRoute
  '/list/classes': typeof ListClassesRoute
  '/list/events': typeof ListEventsRoute
  '/list/exams': typeof ListExamsRoute
  '/list/lessons': typeof ListLessonsRoute
  '/list/messages': typeof ListMessagesRoute
  '/list/parents': typeof ListParentsRoute
  '/list/results': typeof ListResultsRoute
  '/list/students': typeof ListStudentsRoute
  '/list/subjects': typeof ListSubjectsRoute
  '/list/teachers': typeof ListTeachersRoute
  '/report-card/$studentId': typeof ReportCardStudentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/parent': typeof ParentRoute
  '/profile': typeof ProfileRoute
  '/school': typeof SchoolRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/student': typeof StudentRoute
  '/teacher': typeof TeacherRoute
  '/list/announcements': typeof ListAnnouncementsRoute
  '/list/assignments': typeof ListAssignmentsRoute
  '/list/attendance': typeof ListAttendanceRoute
  '/list/classes': typeof ListClassesRoute
  '/list/events': typeof ListEventsRoute
  '/list/exams': typeof ListExamsRoute
  '/list/lessons': typeof ListLessonsRoute
  '/list/messages': typeof ListMessagesRoute
  '/list/parents': typeof ListParentsRoute
  '/list/results': typeof ListResultsRoute
  '/list/students': typeof ListStudentsRoute
  '/list/subjects': typeof ListSubjectsRoute
  '/list/teachers': typeof ListTeachersRoute
  '/report-card/$studentId': typeof ReportCardStudentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/parent'
    | '/profile'
    | '/school'
    | '/settings'
    | '/sign-in'
    | '/student'
    | '/teacher'
    | '/list/announcements'
    | '/list/assignments'
    | '/list/attendance'
    | '/list/classes'
    | '/list/events'
    | '/list/exams'
    | '/list/lessons'
    | '/list/messages'
    | '/list/parents'
    | '/list/results'
    | '/list/students'
    | '/list/subjects'
    | '/list/teachers'
    | '/report-card/$studentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/parent'
    | '/profile'
    | '/school'
    | '/settings'
    | '/sign-in'
    | '/student'
    | '/teacher'
    | '/list/announcements'
    | '/list/assignments'
    | '/list/attendance'
    | '/list/classes'
    | '/list/events'
    | '/list/exams'
    | '/list/lessons'
    | '/list/messages'
    | '/list/parents'
    | '/list/results'
    | '/list/students'
    | '/list/subjects'
    | '/list/teachers'
    | '/report-card/$studentId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/parent'
    | '/profile'
    | '/school'
    | '/settings'
    | '/sign-in'
    | '/student'
    | '/teacher'
    | '/list/announcements'
    | '/list/assignments'
    | '/list/attendance'
    | '/list/classes'
    | '/list/events'
    | '/list/exams'
    | '/list/lessons'
    | '/list/messages'
    | '/list/parents'
    | '/list/results'
    | '/list/students'
    | '/list/subjects'
    | '/list/teachers'
    | '/report-card/$studentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ParentRoute: typeof ParentRoute
  ProfileRoute: typeof ProfileRoute
  SchoolRoute: typeof SchoolRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  StudentRoute: typeof StudentRoute
  TeacherRoute: typeof TeacherRoute
  ListAnnouncementsRoute: typeof ListAnnouncementsRoute
  ListAssignmentsRoute: typeof ListAssignmentsRoute
  ListAttendanceRoute: typeof ListAttendanceRoute
  ListClassesRoute: typeof ListClassesRoute
  ListEventsRoute: typeof ListEventsRoute
  ListExamsRoute: typeof ListExamsRoute
  ListLessonsRoute: typeof ListLessonsRoute
  ListMessagesRoute: typeof ListMessagesRoute
  ListParentsRoute: typeof ListParentsRoute
  ListResultsRoute: typeof ListResultsRoute
  ListStudentsRoute: typeof ListStudentsRoute
  ListSubjectsRoute: typeof ListSubjectsRoute
  ListTeachersRoute: typeof ListTeachersRoute
  ReportCardStudentIdRoute: typeof ReportCardStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school': {
      id: '/school'
      path: '/school'
      fullPath: '/school'
      preLoaderRoute: typeof SchoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report-card/$studentId': {
      id: '/report-card/$studentId'
      path: '/report-card/$studentId'
      fullPath: '/report-card/$studentId'
      preLoaderRoute: typeof ReportCardStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/teachers': {
      id: '/list/teachers'
      path: '/list/teachers'
      fullPath: '/list/teachers'
      preLoaderRoute: typeof ListTeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/subjects': {
      id: '/list/subjects'
      path: '/list/subjects'
      fullPath: '/list/subjects'
      preLoaderRoute: typeof ListSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/students': {
      id: '/list/students'
      path: '/list/students'
      fullPath: '/list/students'
      preLoaderRoute: typeof ListStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/results': {
      id: '/list/results'
      path: '/list/results'
      fullPath: '/list/results'
      preLoaderRoute: typeof ListResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/parents': {
      id: '/list/parents'
      path: '/list/parents'
      fullPath: '/list/parents'
      preLoaderRoute: typeof ListParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/messages': {
      id: '/list/messages'
      path: '/list/messages'
      fullPath: '/list/messages'
      preLoaderRoute: typeof ListMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/lessons': {
      id: '/list/lessons'
      path: '/list/lessons'
      fullPath: '/list/lessons'
      preLoaderRoute: typeof ListLessonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/exams': {
      id: '/list/exams'
      path: '/list/exams'
      fullPath: '/list/exams'
      preLoaderRoute: typeof ListExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/events': {
      id: '/list/events'
      path: '/list/events'
      fullPath: '/list/events'
      preLoaderRoute: typeof ListEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/classes': {
      id: '/list/classes'
      path: '/list/classes'
      fullPath: '/list/classes'
      preLoaderRoute: typeof ListClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/attendance': {
      id: '/list/attendance'
      path: '/list/attendance'
      fullPath: '/list/attendance'
      preLoaderRoute: typeof ListAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/assignments': {
      id: '/list/assignments'
      path: '/list/assignments'
      fullPath: '/list/assignments'
      preLoaderRoute: typeof ListAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list/announcements': {
      id: '/list/announcements'
      path: '/list/announcements'
      fullPath: '/list/announcements'
      preLoaderRoute: typeof ListAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ParentRoute: ParentRoute,
  ProfileRoute: ProfileRoute,
  SchoolRoute: SchoolRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  StudentRoute: StudentRoute,
  TeacherRoute: TeacherRoute,
  ListAnnouncementsRoute: ListAnnouncementsRoute,
  ListAssignmentsRoute: ListAssignmentsRoute,
  ListAttendanceRoute: ListAttendanceRoute,
  ListClassesRoute: ListClassesRoute,
  ListEventsRoute: ListEventsRoute,
  ListExamsRoute: ListExamsRoute,
  ListLessonsRoute: ListLessonsRoute,
  ListMessagesRoute: ListMessagesRoute,
  ListParentsRoute: ListParentsRoute,
  ListResultsRoute: ListResultsRoute,
  ListStudentsRoute: ListStudentsRoute,
  ListSubjectsRoute: ListSubjectsRoute,
  ListTeachersRoute: ListTeachersRoute,
  ReportCardStudentIdRoute: ReportCardStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
